### ISSUE TITLE
[BUG]멀티모니터 적용시 position 버그

### ISSUE THREAD

**Issue by rumbarum** [johngrib/hammerspoon-config#1]
안녕하세요 종립님, 

이번에 새로 리팩토링하신 코드 적용시 맥에서는 status bar 위치에 컬러박스가 제대로 적용됩니다. 듀얼모니터에서는 듀얼 모니터의 status bar 위치가 아니라 맥에서의 status bar 위치에 맞추어서 적용됩니다.

맥의 최상단이 듀얼모니터의 중간에 위치하면 듀얼 모니터 중간위치에 컬러박스가 나옵니다.

**Comment by johngrib** [comment]
아 그런 경우를 생각하지 못했네요. 고쳤습니다. 제보해주셔서 감사합니다.

**Comment by rumbarum** [comment]
바로 고쳐 주셨네요 듀얼에서 정상 작동 확인했습니다.
